version: '3.8'

services:
  order-service:
    build: ./order-service
    ports:
      - "8001:8000"
    depends_on:
      - postgres-db

  payment-service:
    build: ./payment-service
    ports:
      - "8002:8000"
    depends_on:
      - postgres-db

  shipping-service:
    build: ./shipping-service
    ports:
      - "8003:8000"
    depends_on:
      - postgres-db

  product-service:
    build: ./product-service
    ports:
      - "8004:8000"
    depends_on:
      - postgres-db

  user-service:
    build: ./user-service
    ports:
      - "8005:8000"
    depends_on:
      - postgres-db

  ui-service:
    build: ./ui-service
    ports:
      - "3000:3000"

  postgres-db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ecommerce
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
