pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                git url: 'https://github.com/jeevanthomaskorah22/Services', branch: 'main'
            }
        }

        stage('Run with Docker Compose') {
            steps {
                dir('payment-service') {
                    script {
                        bat "docker-compose down || exit 0"
                        bat "docker-compose up --build -d"
                    }
                }
            }
        }
    }

    post {
        always {
            echo "Cleaning up..."
            dir('payment-service') {
                bat "docker-compose down"
            }
            bat "docker system prune -f"
        }
    }
}
